name: crowdmint worker

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

concurrency: 
  group: run-crowdmint-worker
  cancel-in-progress: false

jobs:
  run-crowdmint-worker:
    name: run-crowdmint-worker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
    - run: yarn install
    - run: npm install -g typescript
    - run: cd ./workers/cmd
    - run: tsc main.ts --esModuleInterop
    - run: node main.js