name: crowdmint worker

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

jobs:
  run-crowdmint-worker:
    name: run-crowdmint-worker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
        cache-dependency-path: ./workers/yarn.lock
    - name: setup
      working-directory: ./workers
      run: yarn install
    - name: compile and run
      working-directory: ./workers
      run: npx ts-node -P tsconfig.commonjs.json ./src/main.ts
      env:
        PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}  
        PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}      
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'workers: update data'